### ISSUE TITLE
Fix Dependencies

### ISSUE THREAD

**Issue by ghost** [Heymdall/gulp-angular-jsdoc#1]
## Dependecies jsdoc and through2.

When the plugin is installed, the jsdoc and through2 are not installed like dependencies. 
![captura de tela de 2016-10-10 13-35-10](https://cloud.githubusercontent.com/assets/11689932/19245354/9dff0fca-8eee-11e6-924a-a7398e3f2884.png)

**Comment by Heymdall** [comment]
fixed in v0.1.6
