### ISSUE TITLE
Fix Path

### ISSUE THREAD

**Issue by ghost** [Heymdall/gulp-angular-jsdoc#2]
## Path angular-jsdoc

The plugin angular-jsdoc was updated.

![captura de tela de 2016-10-10 13-42-59](https://cloud.githubusercontent.com/assets/11689932/19245626/1a1a1374-8ef0-11e6-8ddf-0ea993ec0bc7.png)

Need change it

![captura de tela de 2016-10-10 13-42-02](https://cloud.githubusercontent.com/assets/11689932/19245676/5612466c-8ef0-11e6-9aff-67a28860c286.png)

to 

![captura de tela de 2016-10-10 13-51-22](https://cloud.githubusercontent.com/assets/11689932/19245748/cf5f58f2-8ef0-11e6-8323-a1849af45a75.png)

**Comment by Heymdall** [comment]
fixed in v0.1.6
